server:
  port: 8080

# database
spring:
  datasource:
    url: jdbc:mysql://tododb.cyp7o4qafe9k.us-east-2.rds.amazonaws.com:3306/TodoDB
    username: ENC(Ah4kj23TqfZK5MeATmwIdw==)
    password: ENC(AZM6OaTFMJdApOM4ude4BrIVtvPXsSML)
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    database: mysql
    open-in-view: false
    hibernate:
      ddl-auto: none
        #데이터베이스 초기화 전략을 설정합니다.
        #none
        #아무것도 실행하지 않습니다.
        #create
        #SessionFactory가 시작될 때 기존테이블을 삭제 후 다시 생성합니다.
        #create-drop
        #create와 같으나 SessionFactory가 종료될 때 drop을 실행합니다.
        #update
        #변경된 스키마만 반영합니다.
        #validate
      #엔티티와 테이블이 정상적으로 매핑되었는지만 확인합니다.
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    generate-ddl: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(4fkk2RYq2aEGZnZr5jMVkwhORo5DJ7Cz0zgqkAhXz1Y=)
    password: ENC(iafd8gwVLLUCK0zkQeyarTDEQYLNvygF)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



logging:
  level:
    org:
      hibernate:
        type:
          descriptor:  # SQL에서 물음표로 표기된 부분( bind parameter )을 로그로 출력해서 확인
            sql: trace




mail:
  username: ENC(4fkk2RYq2aEGZnZr5jMVkwhORo5DJ7Cz0zgqkAhXz1Y=)


jasypt:
  encryptor:
    bean: jasyptEncryptor
